#version 430

// local size is defined in shader
layout(local_size_x=256, local_size_y=1, local_size_z=1) in;

// bind two buffers to the shader
layout (binding=0) buffer Vector1
{
	float element1[];
};

layout (binding=1) buffer Vector2
{
	float element2[];
};

void main()
{
	uint id = gl_GlobalInvocationID.x;
	for (int i = 0; i < 1000; i++) {
		element1[id] = id;
		element2[id] = -float(id);
	}
}
